### ISSUE TITLE
Laravel 5.7

### ISSUE THREAD

**Issue by stayallive** [sebdesign/laravel-sri#6]
There I am again :) I noticed 5.7 was already added to composer.json but not tagged yet, would be great if you could tag it now 5.7 is released ❤️

**Comment by sebdesign** [comment]
Hi there! :)

I've just tagged v1.1.0. Please try it out and let me know if anything breaks.

Cheers!

**Comment by stayallive** [comment]
Awesome! At first test on a staging env it looks perfect (already was using `dev-master@dev`), thanks for the quick tag! 💯
